const products = [
  {
    id: 1,
    name: "Blender",
    brand: "Ninja",
    category: "Blenders",
    price: 89.99,
    availabilityStatus: "In Stock",
    description: "A high-speed blender for smoothies, shakes, and soups.",
  },
  {
    id: 2,
    name: "Toaster",
    brand: "Cuisinart",
    category: "Toasters",
    price: 49.99,
    availabilityStatus: "Out of Stock",
    description: "A 4-slice toaster with adjustable browning control.",
  },
  {
    id: 3,
    name: "Air Fryer",
    brand: "Philips",
    category: "Air Fryers",
    price: 129.99,
    availabilityStatus: "In Stock",
    description: "An air fryer that cooks with minimal oil for healthier meals.",
  },
  {
    id: 4,
    name: "Microwave Oven",
    brand: "Panasonic",
    category: "Microwaves",
    price: 199.99,
    availabilityStatus: "In Stock",
    description: "A compact microwave oven with inverter technology for even cooking.",
  },
  {
    id: 5,
    name: "Stand Mixer",
    brand: "KitchenAid",
    category: "Mixers",
    price: 299.99,
    availabilityStatus: "In Stock",
    description: "A versatile stand mixer with multiple attachments for baking.",
  },
  {
    id: 6,
    name: "Coffee Maker",
    brand: "Breville",
    category: "Coffee Makers",
    price: 159.99,
    availabilityStatus: "In Stock",
    description: "A programmable coffee maker with a built-in grinder.",
  },
  {
    id: 7,
    name: "Slow Cooker",
    brand: "Crock-Pot",
    category: "Slow Cookers",
    price: 39.99,
    availabilityStatus: "In Stock",
    description: "A slow cooker for making stews, soups, and tender meat dishes.",
  },
  {
    id: 8,
    name: "Electric Kettle",
    brand: "Hamilton Beach",
    category: "Kettles",
    price: 29.99,
    availabilityStatus: "In Stock",
    description: "A stainless steel electric kettle with auto shut-off.",
  },
  {
    id: 9,
    name: "Food Processor",
    brand: "Cuisinart",
    category: "Food Processors",
    price: 99.99,
    availabilityStatus: "In Stock",
    description: "A multi-functional food processor with various slicing blades.",
  },
  {
    id: 10,
    name: "Juicer",
    brand: "Omega",
    category: "Juicers",
    price: 149.99,
    availabilityStatus: "In Stock",
    description: "A slow masticating juicer for fresh, nutrient-rich juice.",
  },
  {
    id: 11,
    name: "Rice Cooker",
    brand: "Zojirushi",
    category: "Rice Cookers",
    price: 129.99,
    availabilityStatus: "In Stock",
    description: "An advanced rice cooker with multiple cooking functions.",
  },
  {
    id: 12,
    name: "Waffle Maker",
    brand: "Dash",
    category: "Waffle Makers",
    price: 39.99,
    availabilityStatus: "In Stock",
    description: "A non-stick waffle maker with quick heating technology.",
  },
  {
    id: 13,
    name: "Electric Griddle",
    brand: "Presto",
    category: "Griddles",
    price: 49.99,
    availabilityStatus: "In Stock",
    description: "A large non-stick griddle for pancakes, bacon, and more.",
  },
  {
    id: 14,
    name: "Hand Mixer",
    brand: "Hamilton Beach",
    category: "Mixers",
    price: 24.99,
    availabilityStatus: "Out of Stock",
    description: "A lightweight hand mixer with multiple speed settings.",
  },
  {
    id: 15,
    name: "Immersion Blender",
    brand: "Braun",
    category: "Blenders",
    price: 59.99,
    availabilityStatus: "In Stock",
    description: "A hand-held immersion blender for soups and smoothies.",
  },
  {
    id: 16,
    name: "Deep Fryer",
    brand: "T-fal",
    category: "Fryers",
    price: 79.99,
    availabilityStatus: "In Stock",
    description: "An electric deep fryer with an oil filtration system.",
  },
  {
    id: 17,
    name: "Ice Cream Maker",
    brand: "Cuisinart",
    category: "Ice Cream Makers",
    price: 69.99,
    availabilityStatus: "In Stock",
    description: "An easy-to-use ice cream maker for homemade frozen treats.",
  },
  {
    id: 18,
    name: "Pressure Cooker",
    brand: "Instant Pot",
    category: "Pressure Cookers",
    price: 119.99,
    availabilityStatus: "In Stock",
    description: "A versatile electric pressure cooker with multiple functions.",
  },
  {
    id: 19,
    name: "Bread Maker",
    brand: "Zojirushi",
    category: "Bread Makers",
    price: 229.99,
    availabilityStatus: "In Stock",
    description: "A high-quality bread maker with customizable settings.",
  },
  {
    id: 20,
    name: "Popcorn Maker",
    brand: "West Bend",
    category: "Popcorn Makers",
    price: 34.99,
    availabilityStatus: "In Stock",
    description: "An electric popcorn maker for quick and easy snacks.",
  },
];

export default products;